# ====================================================
# ARTONIUM - SISTEMA DE PERSONAGENS TORMENTA 20
# ====================================================

services:
  # ====================================================
  # API .NET 8
  # ====================================================
  artonium-api:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: artonium-api
    ports:
      - "5000:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
    volumes:
      - .:/app
      - /app/bin
      - /app/obj
    networks:
      - artonium-network
    restart: unless-stopped
    depends_on:
      - mongo
    develop:
      watch:
        - action: rebuild
          path: .
          ignore:
            - bin/
            - obj/

  # ====================================================
  # BANCO DE DADOS MONGODB
  # ====================================================
  mongo:
    image: mongo:7
    container_name: artonium-mongo
    environment:
      MONGO_INITDB_DATABASE: artonium
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - artonium-network
    restart: unless-stopped

# ====================================================
# VOLUMES E REDES (MONGODB)
# ====================================================
volumes:
  mongo_data:
    driver: local

networks:
  artonium-network:
    driver: bridge
