# ====================================================
# ARTONIUM - SISTEMA DE PERSONAGENS TORMENTA 20
# ====================================================

services:
  # ====================================================
  # API .NET 8
  # ====================================================
  artonium-api:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: artonium-api
    ports:
      - "5000:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
    volumes:
      - .:/app
      - /app/bin
      - /app/obj
    networks:
      - artonium-network
    restart: unless-stopped
    depends_on:
      - artonium-db
    develop:
      watch:
        - action: rebuild
          path: .
          ignore:
            - bin/
            - obj/

  # ====================================================
  # BANCO DE DADOS POSTGRESQL
  # ====================================================
  artonium-db:
    image: postgres:15
    container_name: artonium-db
    environment:
      POSTGRES_DB: artonium
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - artonium-network
    restart: unless-stopped

# ====================================================
# VOLUMES E REDES
# ====================================================
volumes:
  postgres_data:
    driver: local

networks:
  artonium-network:
    driver: bridge
